[build]
  external_node_modules = ["express"]
  functions = "functions"
  publish = "dist"
  node_bundeler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
